services:
  factorio:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - /opt/factorio:/factorio
    working_dir: /factorio
    init: true
    restart: always
    env_file:
      - path: config
        required: true
      - path: .env
        required: false
